### ISSUE TITLE
Rope bridge textures not transparent where expected

### ISSUE THREAD

**Issue by rckymtnrfc** [Samlegamer/Macaw-s-Bridges-Compat#10]
https://imgur.com/a/hMA6DL3

Redwood vs Oak in the pic

Forge 40.1.19 
Macaw's Bridges 2.0.3
Macaw's Bridges BOP 1.1

**Comment by Samlegamer** [comment]
I had the same problem during the update but it is a bug with the graphic settings that I fixed by deleting its files: 
![file](https://user-images.githubusercontent.com/83614614/172058075-ae7ebe1e-98f5-4a0b-871a-21b3dac53e12.PNG)

![2022-06-05_17 09 31](https://user-images.githubusercontent.com/83614614/172057963-b77653b5-1492-4787-885d-09e7c8bc68fe.png)

**Comment by rckymtnrfc** [comment]
I don't have those files as I'm not using Optifine.
